export default function Head() {
  return (
    <>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta property="og:title" content="Next.js" />
      <meta property="og:image:url" content="https://nextjs.org/og.png" />
      <meta property="og:image:width" content="800" />
      <meta property="og:image:height" content="600" />
      <meta name="robots" content="index" />
    </>
  );
}
